log:
  level: INFO

api:
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: :443

providers:
  docker: true
  file:
    directory: /etc/traefik/dynamic
    watch: true
